#%RAML 0.8
title: "Perf testing api mock"
version: "v1"
baseUri: "https://example.com/api"
protocols: [HTTPS, HTTP]
mediaType: "application/json"

resourceTypes:
  - collection:
      description: Collection of available <<resourcePathName>>.
      get?:
        responses:
          200:
            description: Success!
            body:
              application/json:
                example: "example"
                schema: "schema"

  - collection-item:
      description: Entity representing a <<resourcePathName|!singularize>>
      get?:
        description: |
          Get the <<resourcePathName|!singularize>>
          with <<resourcePathName|!singularize>>Id =
          {<<resourcePathName|!singularize>>Id}
        responses:
          200:
            description: Success!
            body:
              application/json:
                example: "example"
                schema: "schema"

/testdata:

  /address_book:
    type: collection
    get:
      headers: !include schemas/cors_headers.yaml
      responses:
        200:
          body:
            application/json:
              schema:  !include schemas/get_address_book.json
              example: !include examples/get_address_book.json

  /users:
    type: collection
    get:
      headers: !include schemas/cors_headers.yaml
      responses:
        200:
          body:
            application/json:
              schema: !include schemas/get_user_list.json
              example: !include examples/get_user_list.json
     